env:
  browser: true
  commonjs: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    - modules: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
