name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - name: Set up Ruby 3
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Test Suite
      run: |
        sudo apt update
        sudo apt-get -yqq install patch zlib1g-dev liblzma-dev libffi-dev libssl-dev libcurl4-gnutls-dev libxslt-dev
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        yarn install
        bin/cibuild.sh
      env:
        BRIDGETOWN_ENV: test
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
